import Head from 'next/head'
import Image from 'next/image'
import Tabs from '../components/TabComponent'
import 'bootstrap/dist/css/bootstrap.min.css';
import { Button } from 'react-bootstrap';
import { PrismaClient } from '@prisma/client';  
import { useState } from 'react';
import axios from 'axios';
import TabComponent from '../components/TabComponent';

   
const prisma = new PrismaClient();

export default function Home({tab}) {

  console.log(tab)
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TabComponent tab={tab}>

      </TabComponent>
      <Button variant='success' className='btn rounded'><h1 className='text-light'>Add Tab</h1></Button>
      
    </div>
  )
}

export async function getServerSideProps() {
  const tab = await prisma.tab.findMany({
    select: {
      id: true,
      Title: true,
      notes: true,
    },
  });    
  //const post = await prisma.post.findMany({where: {authorId: 1}}); 
  return {
    props: {
      
      tab: tab,  
      
    }
  }
}
